name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  protobuf: ^2.1.0
  grpc: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
  grpcgen:
    path: ../
