name: grpcgen
description: Command-line application for code generation for gRPC clients from gRPC Reflection.
version: 0.1.0+1
repository: https://github.com/xclud/dart_grpcgen
homepage: https://pwa.ir

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  protobuf: ^3.0.0
  grpc: ^3.2.1
  fixnum: ^1.1.0
  path: ^1.8.3
  recase: ^4.1.0
  dart_style: ^2.3.1
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0

executables:
  grpcgen:
